### ISSUE TITLE
[REQUEST] Gridlerde kayıt yoksa "Kayıt bulunamadı" mesajı görüntülensin

### ISSUE THREAD

**Issue by onurakkaya** [DogusTeknoloji/DSM-UI-Solution#12]
**Is your feature request related to a problem? Please describe.**
Gridlerde hiç kayıt yoksa görsel olarak kötü bir görünüm oluşuyor.

**Describe the solution you'd like**
Gridlerde hiç kayıt yoksa, "Kayıt Bulunamadı" mesajı görüntülenmesi.

**Comment by furkanevrenguzel** [comment]
İstek çözülmüştür.
