### ISSUE TITLE
[FEATURE] Server detay sayfasında Sunucu powerstate'in görüntülenmesi

### ISSUE THREAD

**Issue by onurakkaya** [DogusTeknoloji/DSM-UI-Solution#64]
- Sunucu detay sayfasında sağ üstte yer alan Powerstate bilgisi, dinamik olarak available ve unavailable olarak güncellenmeli, duruma göre ikon ve renk değişiklikleri yapılmalıdır.
- Sunucunun unavailable olduğu durumlarda kısa bir açıklama mesajı yazılmalıdır.

Örnek; 
Unavailable
![image](https://user-images.githubusercontent.com/24228123/129560757-6107294c-4f8e-41b5-992d-f052de37839e.png)

Available
![image](https://user-images.githubusercontent.com/24228123/129560879-8c89e94e-a1d0-45cc-8b08-d719c85369fd.png)

**Comment by furkanevrenguzel** [comment]
X#64

**Comment by furkanevrenguzel** [comment]
x#64

**Comment by furkanevrenguzel** [comment]
X #64
